import image from "../../assets/Images/a.jpg";

export const patientData = [
  {
    id: 1,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 20,
    name: "John Doe",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Asthma",
    status: "In Treatment",
    img: image,
  },
  {
    id: 2,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 40,
    name: "Jane Smith",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Dental Care",
    status: "New Patient",
    img: image,
  },
  {
    id: 3,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 10,
    name: "Mark White",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Cold & Flu",
    status: "In Treatment",
    img: image,
  },
  {
    id: 4,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 55,
    name: "Shawn Hampton",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Cold & Flu",
    status: "Recovered",
    img: image,
  },
  {
    id: 5,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 15,
    name: "Polly Paul",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Dental Care",
    status: "In Treatment",
    img: image,
  },
  {
    id: 6,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 25,
    name: "Mark Hall",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Asthma",
    status: "New Patient",
    img: image,
  },
  {
    id: 7,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 45,
    name: "Bill Gate",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Dental Care",
    status: "In Treatment",
    img: image,
  },
  {
    id: 8,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 35,
    name: "Ashely Cole",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Diabetes",
    status: "Recovered",
    img: image,
  },
  {
    id: 9,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 5,
    name: "Alicia Keys",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Covid-19 Suspect",
    status: "In Treatment",
    img: image,
  },
  {
    id: 10,
    dateCheckedIn: "01/08/2024",
    time: "10:30 AM",
    roomNo: 52,
    name: "Ben White",
    doctorAssigned: "Dr. Widan Cheeh",
    disease: "Diabetes",
    status: "New Patient",
    img: image,
  },
];
